### ISSUE TITLE
Handle ctrl+S in monaco editor

### ISSUE THREAD

**Issue by kirjs** [codelab-fun/codelab#1033]
While we run the code on every keystroke, lot of user still hit ctrl+S by instinct and get a file save dialog. 

We should prevent the dialog from showing, and maybe show some little animation saying everything is saved (so that the user feels nice)

**Comment by kirjs** [comment]
To reproduce go to https://codelab.fun/angular/typescript/typescript-why-ts and hit ctrl+s

**Comment by jatinAroraGit** [comment]
Hey there,
I would like to work on this.

**Comment by NothingEverHappens** [comment]
Hey @jatinAroraGit that's awesome, I'm not exactly sure what would be the best way to handle this. 

The global configuration is here:
https://github.com/codelab-fun/codelab/blob/57c7b13dd7520581c32e6b12546e2cf1fc4e5c6c/libs/code-demos/src/lib/shared/monaco-config.service.ts#L24

The actual editor instantiation happens here:
https://github.com/codelab-fun/codelab/blob/57c7b13dd7520581c32e6b12546e2cf1fc4e5c6c/libs/code-demos/src/lib/multitab-editor/editor-from-model/editor-from-model.component.ts#L41

Feel free to ping this thread if you're stuck at any point or with any other questions

**Comment by jatinAroraGit** [comment]
Hey @NothingEverHappens,
So I  have figured out most of it and have stopped popping of Save Window. Currently nothing is being displayed on pressing Ctrl+S, Do you want me to implement something to show ctrl+s doing something (like one of those alert boxes with message 'Saved' ) or leave it as it is ?

**Comment by kirjs** [comment]
How about if anything was changed, we can show a snack bar saying everything was saved successfully?

https://material.io/components/snackbars/

**Comment by jatinAroraGit** [comment]
Sounds good, @kirjs .
