### ISSUE TITLE
When the window listing tests is too small there's no ability to scroll

### ISSUE THREAD

**Issue by NothingEverHappens** [codelab-fun/codelab#1067]
# What the issue is about

There's no scroll for the list of tests if the screen is too small: 
![image](https://user-images.githubusercontent.com/216412/65887303-65974700-e3a6-11e9-9147-9469afedef95.png)

# How to start 

Go to the slide: [Local](http://localhost:4200/angular/typescript/exercise-new),[Public](https://angular-presentation.firebaseapp.com/angular/typescript/exercise-new)

Click "see all steps"

Resize the window to be smaller small enough.

# Where's the code
https://github.com/codelab-fun/codelab/blob/master/apps/codelab/src/app/components/exercise/exercise.component.ts

**Comment by jatinAroraGit** [comment]
Hey there, 
I can work on this.

**Comment by bokub** [comment]
I've submitted a PR to fix this

_Sorry @jatinAroraGit but I figured you changed your mind as you didn't give any update in 3 days 🤷‍♂_
