### ISSUE TITLE
Mat buttons module not imported

### ISSUE THREAD

**Issue by kirjs** [codelab-fun/codelab#1089]
# What is this about?
This issue should be very easy to fix:

Buttons on the screenshot are not material, because example does not import the module.
<img width="1496" alt="mat-button" src="https://user-images.githubusercontent.com/2545357/66277834-d5f40b80-e871-11e9-9565-0c04cf78ed4f.png">

# Simple fix
1. Reproduce issue Slide: [Locally](http://localhost:4200/angular/material/themes) or [in prod](https://angular-presentation.firebaseapp.com/angular/material/themes)

2. Find the file and add MatButton module. It think it's here:
apps/codelab/src/app/codelabs/angular/material/samples/basic/app.module.ts

3. Verify it does not show up in other slides where it shouldn't be (e.g. before we talk about buttons)

# Fun fix
It would be cool to point the missing module to user, and ask the user to import the module, it seems like more fun and more work

**Comment by klauskpm** [comment]
I would like to work on this

**Comment by NothingEverHappens** [comment]
Go for it
