### ISSUE TITLE
[Feedback] Normalize URLs

### ISSUE THREAD

**Issue by kirjs** [codelab-fun/codelab#1090]
Few things:

1. New urls have double angular in them and don't work (angular/angular)
![image](https://user-images.githubusercontent.com/2545357/66277753-fd96a400-e870-11e9-88e9-199d1a659e1f.png)

2. When creating an issue, both local/public links are broken on the issue (missing /angular/)
![image](https://user-images.githubusercontent.com/2545357/66277773-346cba00-e871-11e9-87f5-cf76fb2e5b52.png)

3. When creating an issue, public link should use codelab.fun URL (not the old one)

**Comment by NothingEverHappens** [comment]
I fixed this
