### ISSUE TITLE
[Russian translations] Fix broken translations

### ISSUE THREAD

**Issue by kirjs** [codelab-fun/codelab#1103]
# What the issue is about
Some of russian translation strings have broken structure (missing < or >, etc).

Would be great to fix it

# How to start
Search in `codelab.ru.xtb` for  `/>`
![image](https://user-images.githubusercontent.com/2545357/66314081-7897a300-e8e1-11e9-8ebd-2947d340fa07.png)

Find appropriate ID in poeditor and fix the translation

# Old context

There are several strings which are properly translated to russian, but did not made it to the translation file.

I create an issue for it, can be tracked [here](https://poeditor.uservoice.com/forums/171919-general/suggestions/38701054-one-translation-term-being-exported-as-empty-despi?tracking_code=30626ee8255717dd4a3da5f6dc892e5c)
Author: Алексей
Slide: [Local](http://localhost:4200/angular/create-first-app/bootstrap),[Public](https://angular-presentation.firebaseapp.com/ru/angular/create-first-app/bootstrap)

**Comment by tplk** [comment]
@kirjs привет, а как в POEditor поглядеть переводы?

**Comment by tplk** [comment]
Битые строки я погрепал, могу сам перевести, но как я понял - в сервисе переводы уже должны быть.

**Comment by NothingEverHappens** [comment]
I'd have to add you to the dashboard, just pinged you on telegram
