### ISSUE TITLE
The code above is editable! overlaps with the exercise

### ISSUE THREAD

**Issue by kirjs** [codelab-fun/codelab#1105]
# What the issue is about
The code above is editable! overlaps with the exercise

![image](https://user-images.githubusercontent.com/2545357/66278296-a8a95c80-e875-11e9-8e17-3626f151b4af.png)

# Where to start
Reproduce  [Locally](http://localhost:4200/angular/typescript/typescript-mini-exercise)

Figure out why overlap happens, this may require some understanding of CSS and changes on the code-demo component level

# Meta

Author: Дмитрий
Slide: [Local](http://localhost:4200/angular/typescript/typescript-mini-exercise),[Public](https://angular-presentation.firebaseapp.com/angular/typescript/typescript-mini-exercise)

**Comment by klauskpm** [comment]
I would like to work on this

**Comment by NothingEverHappens** [comment]
I'd say let's go one by one, I assigned you the other issue you pinged

**Comment by bautistaaa** [comment]
can I take this one?

**Comment by NothingEverHappens** [comment]
I'd say let's go in order, @klauskpm are you still interested?
@bautistaaa If this is taken I'd be happy to help you find another issue which is not super complex

**Comment by klauskpm** [comment]
Yes. I'll work on it.

**Comment by bautistaaa** [comment]
no problem, only inquired cause it looked like he was working on something else. let me know how I can help!

**Comment by NothingEverHappens** [comment]
@bautistaaa how about this one: https://github.com/codelab-fun/codelab/issues/1117 ?

**Comment by bautistaaa** [comment]
sure!
