### ISSUE TITLE
Diagram does not scale well

### ISSUE THREAD

**Issue by kirjs** [codelab-fun/codelab#1117]
# What the issue is about
This diagram does not scale really well with the rest of the page.

![image](https://user-images.githubusercontent.com/2545357/66278747-325b2900-e87a-11e9-9dba-cc4ca6a652e3.png)

# Where to start?
Start with reproducing [Locally](http://localhost:4200/angular/dependency-injection/dependency-injection-intro)

Search for the diagram in the code. Filename is ./pics/deps.svg
The reason it's included in CSS is that CSS actually inlines it (using img tag would be possible, but more painful)

As an alternative options - consider creating an angular component with svg as a template

# Metadata:
This was filed through the feedback form.
Author: pavel
Date: Sat, 23 Feb 2019 09:56:00 GMT
Slide: [Local](http://localhost:4200/angular/dependency-injection/dependency-injection-intro),[Prod](https://codelab.fun/angular/dependency-injection/dependency-injection-intro)

**Comment by NothingEverHappens** [comment]
cc @bautistaaa who expressed interest

**Comment by kirjs** [comment]
@bautistaaa, I'm assigning to myself to indicate it's taken, I can reassign to you once you add a comment to this issue.

Also if you change your mind at any point, just lmk

**Comment by bautistaaa** [comment]
i can take a look at this today @kirjs

**Comment by kirjs** [comment]
Would you mind attaching a couple of screenshots?

**Comment by NothingEverHappens** [comment]
This has been fixed
