### ISSUE TITLE
[Prototype] Can we run monaco outside of the zone?

### ISSUE THREAD

**Issue by NothingEverHappens** [codelab-fun/codelab#1141]
# What the issue is about
Monaco has lots of event listeners, and we run it inside of zone which (probably) adds overhead 

# Where to start
Read about zone.js 
https://blog.thoughtram.io/angular/2017/02/21/using-zones-in-angular-for-better-performance.html

Search for usages of 
https://github.com/codelab-fun/codelab/blob/master/libs/code-demos/src/lib/shared/monaco-config.service.ts

**Comment by antkiewicz** [comment]
I will play around with this. This will be a good opportunity to dive deeper into zones.
