### ISSUE TITLE
Validate broken Russian translations

### ISSUE THREAD

**Issue by kirjs** [codelab-fun/codelab#1144]
# What the issue is about
If there's an error in translation (e.g. matching brace), poeditor just exports it as an empty string without any warnings.

![image](https://user-images.githubusercontent.com/2545357/66524374-4b551b80-eac0-11e9-9116-0d9b094c16bf.png)

We currently fixed all of broken translations (#1103) 

But would be amazing to get a warning next time a broken translation exist

# Where to start 
https://github.com/codelab-fun/codelab/blob/master/apps/codelab/src/locale/codelab.ru.xtb

Create a script that scans for empty strings, and throws an error if they exist in a file

Add pre-commit hook

**Comment by tplk** [comment]
What's the current behavior if there's no translation present?
E.g. I create a new lesson in English (therefore adding new messages in `messages.xmb`) and export 
`codelab.ru.xtb` without actually adding new translations. Is POEditor going to add empty messages into the file or omit the missing ones?

In case it just adds empty messages we can't rely on it to detect broken ones.

**Comment by tplk** [comment]
There's an option to export only translated terms though:
![image](https://user-images.githubusercontent.com/20531968/66575656-f7f5d280-eb7e-11e9-97af-fb8e9b5d989e.png)

```xml
<translationbundle lang="ru">
  <translation id="4652524240777426119">нормальный</translation>
  <translation id="4488553771617997081"/>
</translationbundle>
```

**Comment by kirjs** [comment]
Hm, good catch! 
I think it mostly comes down to how we do #1145
