### ISSUE TITLE
[Prototype] Move file changes processing to web worker

### ISSUE THREAD

**Issue by antkiewicz** [codelab-fun/codelab#1206]
Currently debounced monaco changes are processed through few observable streams. Static files have simpler path, while TS runs through extra compilation step. This has negative performance effect on UI performance.

https://github.com/codelab-fun/codelab/blob/master/libs/code-demos/src/lib/code-demo/code-demo.component.ts#L76

Perhaps we can consider moving those operation to a worker to help free up main thread.

**Comment by NothingEverHappens** [comment]
Before we get to prototyping it would be really cool to measure current performance and get some numbers out there to understand where we stand

**Comment by NothingEverHappens** [comment]
Closing this issue after chatting offline
