### ISSUE TITLE
Hard to tell what I should do when it's all green. 
I know that it says "Go to the next slide" but that's hard to notice. 

### ISSUE THREAD

**Issue by kirjs** [codelab-fun/codelab#236]
# What the issue is about?
Once the user has completed all tests, we should celebrate it, and let the user know they should go to the next slide.

Maybe show funny gif and "Go to the next step" message

![image](https://user-images.githubusercontent.com/216412/66335419-01760500-e909-11e9-82ea-51560fba1151.png)

# How to start
Start by reproducing the issue with [typescript exercise](http://localhost:4200/angular/typescript/exercise-new), click "load solution" button

This has already been fixed in #72, but then this code got lost :(

# Some old context
Hard to tell what I should do when it's all green. 
I know that it says "Go to the next slide" but that's hard to notice.  
Author: John Paul
[Slide](http://localhost:4200/templates/exercise)

**Comment by kirjs** [comment]
Related to #72 #181 starts to address

**Comment by tessaSAC** [comment]
Closing since it seems like it will be resolved by #72

**Comment by NothingEverHappens** [comment]
This has been solved in #72, but then the code got lost somehow :(

**Comment by MaxFlower** [comment]
@kirjs May I take this issue as my first one?

**Comment by kirjs** [comment]
You got it
