### ISSUE TITLE
Add a better feedback page

### ISSUE THREAD

**Issue by kirjs** [codelab-fun/codelab#998]
`npm start`
go to http://localhost:4200/extra/feedback-page/main
This is the old page, it looks ugly and is not very useful.

It should be:
1. Moved to the admin panel
2. Hide behind the permission
3. Use some kind of table (mat-table or anything else?)

**Comment by kirjs** [comment]
`apps/codelab/src/app/codelabs/extra/feedback-page`

**Comment by NothingEverHappens** [comment]
Closing
